name: whiskers check
on:
  push:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: catppuccin/whiskers/.github/workflows/check.yml@ci/reusable-action
        with:
          templates: zed.tera
        secrets: inherit
