name: Whiskers Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: catppuccin/setup-whiskers@v1
        with:
          whiskers-version: 2.5.1
      - run: |
          whiskers zed.tera --overrides '{\"accent\": [\"mauve\"]}' --check
