on:
    workflow_dispatch:
    push:
      branches: [main]
  
name: CI
  
permissions:
    contents: read
    pull-requests: write

jobs:
    run-whiskers:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.1
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: use cutting edge whiskers
          run: cargo install --git https://github.com/catppuccin/toolbox catppuccin-whiskers
        - id: whiskers-check
          run: whiskers template.hbr all --check themes/catppuccin.json
          env:
            NO_COLOR: true
        # Save the output of the command as a text artifact only if stdout is not empty
        - if: success() && grep -q . ${{ steps.whiskers-check.outputs.stdout }}
          uses: actions/upload-artifact@v2
          with:
            name: diffs
            path: ${{ steps.whiskers-check.outputs.stdout }}