name: publish

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  accents-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      # install whiskers
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo-binstall catppuccin-whiskers@2.4.0 -y

      # run whiskers
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: |
          $HOME/.cargo/bin/whiskers zed.tera -o json
          find themes -type f | tr '\n' ' ' >> $GITHUB_OUTPUT

      # view all accents in ci
      - name: upload accents
        uses: actions/upload-artifact@v2
        with:
          name: catppuccin-zed-${{ github.sha }}
          path: themes/catppuccin-*.json

      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ needs.release-please.outputs.tag_name }}" ${{ steps.build.outputs.binary }}

  zed-publish:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: catppuccin
          push-to: ${{ vars.FORKED_REPO_HANDLE }}
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
